spotify_dbt_data_pipeline:
  target: dev

  outputs:
    dev:
      type: postgres
      dbname: "{{ env_var('POSTGRES_DW_DB') }}"
      host: host.docker.internal
      user: "{{ env_var('POSTGRES_DW_USER') }}"
      password: "{{ env_var('POSTGRES_DW_PASSWORD') }}"
      port: 5434
      schema: "{{ env_var('POSTGRES_DW_PASSWORD') }}"
      threads: 10

    prod:
      type: postgres
      dbname: "{{ env_var('POSTGRES_DW_DB') }}"
      host: "{{ env_var('POSTGRES_DW_HOST') }}"
      user: "{{ env_var('POSTGRES_DW_USER') }}"
      password: "{{ env_var('POSTGRES_DW_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_DW_PORT') }}"
      schema: "{{ env_var('POSTGRES_DW_SCHEMA') }}"
      threads: 10
